name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  flutter_version: "1.15.17"
  java_version: "12.x"

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Install dependencies
      run: flutter pub get
    - name: Build apk
      run: flutter build apk

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app-release-${GITHUB_SHA::8}.apk
        path: ./build/app/outputs/apk/release/app-release.apk
