name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: steebchen/flutter@v1.0.0
    - name: Install dependencies
      run: flutter pub get
    - name: Build apk
      run: flutter build apk

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app-release-${GITHUB_SHA::8}.apk
        path: ./build/app/outputs/apk/release/app-release.apk
